# Generated by Django 3.0.6 on 2020-05-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This is title for u issue', max_length=120)),
                ('message', models.TextField(help_text="What's on your mind...")),
            ],
        ),
    ]
